name: Atualizar capa Record

on:
  schedule:
    - cron: "1 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull antes de tudo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Instalar dependÃªncias
        run: pip install requests beautifulsoup4

      - name: Executar script
        run: python baixar_record_capa.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizar capa Record automaticamente"
          file_pattern: record-capa.jpg
          branch: main

